### ISSUE TITLE
目录结构建议

### ISSUE THREAD

**Issue by SunSeaLucky** [Indolent-Kawhi/XJU-Computing-Heart#8]
1. 建议改变结构，不要分大一、大二，直接分课程，便于寻找；
2. 建议删除无用文件，让整个目录结构整理得看起来更有序；
3. 课程写全名而非缩写，如不写`高数`，而写`高等数学`。

**Comment by Indolent-Kawhi** [comment]
谢谢你的意见，可以修改后提个 PR

**Comment by Indolent-Kawhi** [comment]
已修改
